# 1. Data Preprocessing

## 1.1 Import Dependencies

In [1]:
import math
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import os
from collections import defaultdict
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler

In [2]:
for dirname, _, filenames in os.walk('./data'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

./data/test_round2.csv
./data/.DS_Store
./data/train_round2.csv
./data/graph_round2.csv
./data/test.csv
./data/graph.csv
./data/submission_round2.csv
./data/submission.csv
./data/train.csv


## 1.2 Load Data

In [3]:
data_dir = 'data'
temporal_data_path = os.path.join(data_dir, 'train.csv')
mobility_data_path = os.path.join(data_dir, 'graph_round2.csv')

temporal_data = pd.read_csv(temporal_data_path)
temporal_data.describe()
# train_round2.csv 04/12/2020 to 11/22/2020.
# train.csv 04/12/2020 to 08/31/2020

ID      Confirmed        Deaths      Recovered         Active  \
count  7100.000000    7100.000000   7100.000000    5771.000000    7100.000000   
mean   3549.500000   56374.339577   2323.883099   20422.274649   37635.120986   
std    2049.737788   95058.665054   4742.274729   39262.213465   79067.101832   
min       0.000000     270.000000      0.000000       0.000000    -989.000000   
25%    1774.750000    6097.500000    153.000000    1614.500000    2849.000000   
50%    3549.500000   22892.000000    681.000000    5881.000000   10409.000000   
75%    5324.250000   62959.250000   2334.000000   26103.000000   32106.500000   
max    7099.000000  712475.000000  32957.000000  507499.000000  699453.000000   

       Incident_Rate  People_Tested  People_Hospitalized  Mortality_Rate  \
count    7100.000000   7.100000e+03          5047.000000     7100.000000   
mean      747.273790   6.427069e+05          6250.044185        3.653231   
std       637.397470   1.127555e+06         13880.694435        2.074042   
min        32.771004   5.459000e+03            10.000000        0.000000   
25%       224.815702   1.000775e+05           595.000000        1.928925   
50%       540.836745   2.643235e+05          2068.000000        3.362027   
75%      1126.282666   7.048395e+05          6134.500000        4.797564   
max      3187.773001   1.137330e+07         89995.000000        9.741481   

       Testing_Rate  Hospitalization_Rate  
count   7100.000000           5047.000000  
mean    9666.099116             12.197144  
std     7779.560336              5.255183  
min      460.300152              2.302896  
25%     3379.288445              8.387037  
50%     7842.820591             11.351161  
75%    14127.521137             15.396088  
max    49502.860687             38.501190

In [4]:
states = list(np.unique(temporal_data['Province_State']))
state_cum_temporal_data = dict.fromkeys(states, None)
state_temporal_data = dict.fromkeys(states, None)
# state_cum_temporal_scaler = defaultdict(StandardScaler)
# state_temporal_scaler = defaultdict(StandardScaler)
dropped_attr = ['Date',
                'Active',
                'ID', 
                'Province_State', 
                'Incident_Rate', 
                'Recovered', 
                'People_Tested', 
                'People_Hospitalized', 
                'Mortality_Rate', 
                'Testing_Rate', 
                'Hospitalization_Rate']

for s in states:
    df_filter = temporal_data['Province_State'] == s
    state_df = temporal_data[df_filter]
    # Daily difference data
    state_temporal_data[s] = state_df.drop(dropped_attr, 1)
    for col in state_temporal_data[s]:
        data = state_temporal_data[s][col].tolist()
        diff = [i - j for i, j in zip(data, [*[data[0]], *data[:len(data) - 1]])]
        state_temporal_data[s][col] = diff
    save_columns = state_temporal_data[s].columns
#     state_temporal_data[s] = state_temporal_scaler[s].fit_transform(state_temporal_data[s])
    state_temporal_data[s] = pd.DataFrame(state_temporal_data[s], columns=save_columns)
    # Daily cumulative data
    state_cum_temporal_data[s] = state_df.drop(dropped_attr, 1)
    save_columns = state_cum_temporal_data[s].columns
#     state_cum_temporal_data[s] = state_cum_temporal_scaler[s].fit_transform(state_cum_temporal_data[s])
    state_cum_temporal_data[s] = pd.DataFrame(state_cum_temporal_data[s], columns=save_columns)
    
print(state_temporal_data['California'])
print(state_cum_temporal_data['California'])

      Confirmed  Deaths
4             0       0
54         1136      74
104        1425      53
154        1330      93
204         991      96
...         ...     ...
6854       4817     145
6904       5564     128
6954       4653      89
7004       3913      43
7054       6524      85

[142 rows x 2 columns]
      Confirmed  Deaths
4         22795     640
54        23931     714
104       25356     767
154       26686     860
204       27677     956
...         ...     ...
6854     691821   12677
6904     697385   12805
6954     702038   12894
7004     705951   12937
7054     712475   13022

[142 rows x 2 columns]


## Train a RNN Model with LSTM

In [147]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.layers import Dense, LSTM, Dropout
from tensorflow.keras import Sequential
from tensorflow.keras import Input
from tensorflow.keras.models import Model

# window_size is use n-1 days to predict nth day
window_size = 22
forecast_days = 26

# test model for current_state
current_state = 'South Dakota'
data_training = state_temporal_data[current_state]

In [148]:
scaler = MinMaxScaler()
data_training = scaler.fit_transform(data_training)

In [149]:
X_train = []
y_train = []

data_training_np = np.array(data_training)

for i in range(data_training.shape[0] - window_size):
    X_train.append(data_training[i : i + window_size])
    y_train.append(data_training_np[i + window_size])
    
X_train, y_train = np.array(X_train), np.array(y_train)

In [131]:
X_train

array([[[0.27378508, 0.04347826],
        [0.36276523, 0.13043478],
        [0.3340178 , 0.17391304],
        ...,
        [0.31211499, 0.17391304],
        [0.29774127, 0.39130435],
        [0.31827515, 0.2173913 ]],

       [[0.36276523, 0.13043478],
        [0.3340178 , 0.17391304],
        [0.32238193, 0.08695652],
        ...,
        [0.29774127, 0.39130435],
        [0.31827515, 0.2173913 ],
        [0.31074606, 0.2173913 ]],

       [[0.3340178 , 0.17391304],
        [0.32238193, 0.08695652],
        [0.30869268, 0.2173913 ],
        ...,
        [0.31827515, 0.2173913 ],
        [0.31074606, 0.2173913 ],
        [0.29705681, 0.17391304]],

       ...,

       [[0.96577687, 0.30434783],
        [0.80219028, 0.65217391],
        [0.66529774, 0.43478261],
        ...,
        [0.71800137, 0.95652174],
        [0.76796715, 0.34782609],
        [0.84736482, 0.7826087 ]],

       [[0.80219028, 0.65217391],
        [0.66529774, 0.43478261],
        [0.71526352, 0.52173913],
        .

In [150]:
y_train

array([[0.05939005, 0.        ],
       [0.08507223, 0.5       ],
       [0.09470305, 0.83333333],
       [0.20224719, 0.33333333],
       [0.38362761, 0.        ],
       [0.39807384, 0.5       ],
       [0.19903692, 0.        ],
       [0.15569823, 0.        ],
       [0.07865169, 0.83333333],
       [0.11075441, 0.        ],
       [0.09630819, 0.66666667],
       [0.15248796, 0.16666667],
       [0.11556982, 0.        ],
       [0.04494382, 0.        ],
       [0.06420546, 0.        ],
       [0.09309791, 0.33333333],
       [0.14767255, 0.        ],
       [0.        , 0.33333333],
       [0.28731942, 0.33333333],
       [0.17335474, 0.        ],
       [0.15890851, 0.        ],
       [0.03691814, 0.        ],
       [0.10754414, 0.        ],
       [0.09149278, 0.66666667],
       [0.13322632, 0.        ],
       [0.11717496, 0.83333333],
       [0.15088283, 0.5       ],
       [0.0529695 , 0.        ],
       [0.06581059, 0.        ],
       [0.0529695 , 0.        ],
       [0.

In [151]:
model = keras.Sequential()

model.add(LSTM(units=20, activation = 'relu', return_sequences=True, input_shape=(X_train.shape[1], X_train.shape[2])))
model.add(Dropout(0.2))

model.add(LSTM(units=30, activation = 'relu', return_sequences=True))
model.add(Dropout(0.2))

model.add(LSTM(units=40, activation = 'relu', return_sequences=False))
model.add(Dropout(0.2))

model.add(Dense(units = 2))

model.summary()

Model: "sequential_8"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_22 (LSTM)               (None, 22, 20)            1840      
_________________________________________________________________
dropout_22 (Dropout)         (None, 22, 20)            0         
_________________________________________________________________
lstm_23 (LSTM)               (None, 22, 30)            6120      
_________________________________________________________________
dropout_23 (Dropout)         (None, 22, 30)            0         
_________________________________________________________________
lstm_24 (LSTM)               (None, 40)                11360     
_________________________________________________________________
dropout_24 (Dropout)         (None, 40)                0         
_________________________________________________________________
dense_8 (Dense)              (None, 2)                

In [152]:
model.compile(optimizer='adam', loss = 'mean_squared_logarithmic_error')
model.fit(X_train, y_train, epochs=50, batch_size=16, verbose=1)

Train on 120 samples
Epoch 1/50
120/120 [==============================] - 12s 96ms/sample - loss: 0.0415
Epoch 2/50
120/120 [==============================] - 1s 10ms/sample - loss: 0.0372
Epoch 3/50
120/120 [==============================] - 1s 8ms/sample - loss: 0.0366
Epoch 4/50
120/120 [==============================] - 1s 8ms/sample - loss: 0.0366
Epoch 5/50
120/120 [==============================] - 1s 8ms/sample - loss: 0.0366
Epoch 6/50
120/120 [==============================] - 1s 8ms/sample - loss: 0.0365
Epoch 7/50
120/120 [==============================] - 1s 8ms/sample - loss: 0.0364
Epoch 8/50
120/120 [==============================] - 1s 8ms/sample - loss: 0.0362
Epoch 9/50
120/120 [==============================] - 1s 9ms/sample - loss: 0.0359
Epoch 10/50
120/120 [==============================] - 2s 13ms/sample - loss: 0.0360
Epoch 11/50
120/120 [==============================] - 1s 9ms/sample - loss: 0.0359
Epoch 12/50
120/120 [==============================] - 1s 8m

In [153]:
prediction_queue = X_train[-1:]
prediction_queue = np.array(prediction_queue)
prediction_queue

array([[[0.20545746, 0.        ],
        [0.09309791, 0.        ],
        [0.08025682, 0.        ],
        [0.16372392, 0.16666667],
        [0.13162119, 0.16666667],
        [0.20385233, 0.33333333],
        [0.15088283, 0.33333333],
        [0.25040128, 0.16666667],
        [0.13804173, 0.        ],
        [0.13001605, 0.16666667],
        [0.20064205, 0.16666667],
        [0.20064205, 0.33333333],
        [0.30979133, 0.33333333],
        [0.40288925, 0.16666667],
        [0.22632424, 0.16666667],
        [0.23916533, 0.        ],
        [0.12841091, 0.        ],
        [0.105939  , 0.16666667],
        [1.        , 0.        ],
        [0.51845907, 0.5       ],
        [0.68218299, 0.33333333],
        [0.60995185, 0.        ]]])

In [136]:
# prediction_queue should take in this y_pred as the last day and pop the first day in the queue
# use model.predict(prediction_queue) with the new prediction_queue to get second day.
# need to predict for next forecast_days days.
for i in range(forecast_days):  
    y_pred = model.predict(prediction_queue)
    prediction_queue = np.append(prediction_queue, y_pred)
    prediction_queue = np.delete(prediction_queue, 0)
    prediction_queue = np.delete(prediction_queue, 0)
    prediction_queue = prediction_queue.reshape(1,int(prediction_queue.shape[0]/2),2)

prediction_queue

array([[[0.55174327, 0.56135386],
        [0.54735863, 0.56098646],
        [0.54214996, 0.56425303],
        [0.54351187, 0.55921417],
        [0.53842252, 0.57075614],
        [0.53662515, 0.57971072],
        [0.53388244, 0.57318926],
        [0.52781695, 0.56612372],
        [0.5238868 , 0.56303334],
        [0.51557171, 0.54047745],
        [0.51186264, 0.53646958],
        [0.50936419, 0.53180474],
        [0.50722307, 0.53286809],
        [0.50313467, 0.5248214 ],
        [0.49715108, 0.50796896],
        [0.4913041 , 0.50604516],
        [0.48482725, 0.49203867],
        [0.47967643, 0.48025283],
        [0.47718105, 0.47747689],
        [0.47483638, 0.4759523 ],
        [0.47218186, 0.47321808],
        [0.46927962, 0.46955955]]])

In [154]:
y_case_forecast = []
y_death_forecast = []

for i in range(forecast_days):
    y_case_forecast.append(prediction_queue[0][i + window_size - forecast_days][0])
    y_death_forecast.append(prediction_queue[0][i + window_size - forecast_days][1])

In [155]:
y_case_forecast

[1.0,
 0.5184590690208668,
 0.6821829855537721,
 0.6099518459069021,
 0.20545746388443017,
 0.09309791332263243,
 0.08025682182985554,
 0.1637239165329053,
 0.13162118780096307,
 0.20385232744783308,
 0.1508828250401284,
 0.2504012841091493,
 0.13804173354735153,
 0.13001605136436598,
 0.20064205457463885,
 0.20064205457463885,
 0.30979133226324235,
 0.4028892455858748,
 0.22632423756019263,
 0.2391653290529695,
 0.12841091492776885,
 0.10593900481540931,
 1.0,
 0.5184590690208668,
 0.6821829855537721,
 0.6099518459069021]

In [156]:
y_death_forecast

[0.0,
 0.5,
 0.3333333333333333,
 0.0,
 0.0,
 0.0,
 0.0,
 0.16666666666666666,
 0.16666666666666666,
 0.3333333333333333,
 0.3333333333333333,
 0.16666666666666666,
 0.0,
 0.16666666666666666,
 0.16666666666666666,
 0.3333333333333333,
 0.3333333333333333,
 0.16666666666666666,
 0.16666666666666666,
 0.0,
 0.0,
 0.16666666666666666,
 0.0,
 0.5,
 0.3333333333333333,
 0.0]

In [157]:
case_scale = 1/scaler.scale_[0]
death_scale = 1/scaler.scale_[1]

In [158]:
case_scale

623.0

In [159]:
death_scale

6.0

In [160]:
y_case_forecast = [case_scale * i for i in y_case_forecast]
y_death_forecast = [death_scale * i for i in y_death_forecast]

In [161]:
last_day_case = state_cum_temporal_data[current_state]['Confirmed'].iloc[-1]
last_day_death = state_cum_temporal_data[current_state]['Deaths'].iloc[-1]

y_cum_case_forecast = []
y_cum_death_forecast = []

cum_case = last_day_case
cum_death = last_day_death
for case in y_case_forecast:
    cum_case += case
    y_cum_case_forecast.append(cum_case)
    
for death in y_death_forecast:
    cum_death += death
    y_cum_death_forecast.append(cum_death)

In [162]:
y_cum_case_forecast

[14132.0,
 14455.0,
 14880.0,
 15260.0,
 15388.0,
 15446.0,
 15496.0,
 15598.0,
 15680.0,
 15807.0,
 15901.0,
 16057.0,
 16143.0,
 16224.0,
 16349.0,
 16474.0,
 16667.0,
 16918.0,
 17059.0,
 17208.0,
 17288.0,
 17354.0,
 17977.0,
 18300.0,
 18725.0,
 19105.0]

In [163]:
y_cum_death_forecast

[167.0,
 170.0,
 172.0,
 172.0,
 172.0,
 172.0,
 172.0,
 173.0,
 174.0,
 176.0,
 178.0,
 179.0,
 179.0,
 180.0,
 181.0,
 183.0,
 185.0,
 186.0,
 187.0,
 187.0,
 187.0,
 188.0,
 188.0,
 191.0,
 193.0,
 193.0]

# 2. Train a RNN with LSTM for Every State

## 2.1 Import Dependencies

In [ ]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.layers import Dense, LSTM, Dropout
from tensorflow.keras import Sequential
from tensorflow.keras import Input
from tensorflow.keras.models import Model

# window_size is use n-1 days to predict nth day
window_size = 22
forecast_days = 26

## 2.2 Helper Functions

In [ ]:
states = state_temporal_data.keys()

def get_training_data(state):
    state_temporal_train = state_temporal_data[state]
    scaler = MinMaxScaler()
    state_temporal_train = scaler.fit_transform(state_temporal_train)
    
    X_train = []
    y_train = []

    state_temporal_train_np = np.array(state_temporal_train)

    for i in range(state_temporal_train.shape[0] - window_size):
        X_train.append(state_temporal_train[i : i + window_size])
        y_train.append(state_temporal_train_np[i + window_size])

    return np.array(X_train), np.array(y_train), scaler
    

def get_model(X_train):
    model = keras.Sequential()

    model.add(LSTM(units=20, activation = 'relu', return_sequences=True, input_shape=(X_train.shape[1], X_train.shape[2])))
    model.add(Dropout(0.2))

    model.add(LSTM(units=30, activation = 'relu', return_sequences=True))
    model.add(Dropout(0.2))

    model.add(LSTM(units=40, activation = 'relu', return_sequences=False))
    model.add(Dropout(0.2))

    model.add(Dense(units = 2))
    
    return model


def get_prediction_queue(X_train):
    prediction_queue = X_train[-1:]
    return np.array(prediction_queue)


def predict(model, queue, scaler):
    prediction_queue = queue
    
    for i in range(forecast_days):  
        y_pred = model.predict(prediction_queue)
        prediction_queue = np.append(prediction_queue, y_pred)
        prediction_queue = np.delete(prediction_queue, 0)
        prediction_queue = np.delete(prediction_queue, 0)
        prediction_queue = prediction_queue.reshape(1, prediction_queue.shape[0] // 2, 2)
        
    y_case_forecast = []
    y_death_forecast = []

    for i in range(forecast_days):
        y_case_forecast.append(prediction_queue[0][i + window_size - forecast_days][0])
        y_death_forecast.append(prediction_queue[0][i + window_size - forecast_days][1])
        
    case_scale = 1 / scaler.scale_[0]
    death_scale = 1 / scaler.scale_[1]
    
    return [case_scale * i for i in y_case_forecast], [death_scale * i for i in y_death_forecast]


def get_cum_forecast(state, y_case_forecast, y_death_forecast):
    last_day_case = state_cum_temporal_data[state]['Confirmed'].iloc[-1]
    last_day_death = state_cum_temporal_data[state]['Deaths'].iloc[-1]

    y_cum_case_forecast = []
    y_cum_death_forecast = []

    cum_case = last_day_case
    cum_death = last_day_death
    for case in y_case_forecast:
        cum_case += case
        y_cum_case_forecast.append(cum_case)

    for death in y_death_forecast:
        cum_death += death
        y_cum_death_forecast.append(cum_death)
        
    return y_cum_case_forecast, y_cum_death_forecast

## 2.3 Train and Predict

In [ ]:
forecasted = {}

for state in states:
    X_train, y_train, scaler = get_training_data(state)

    model = get_model(X_train)
    model.compile(optimizer='adam', loss = 'mean_squared_logarithmic_error')
    model.fit(X_train, y_train, epochs=50, batch_size=16)
    
    y_case_forecast, y_death_forecast = predict(model, get_prediction_queue(X_train), scaler)
    y_cum_case_forecast, y_cum_death_forecast = get_cum_forecast(state, y_case_forecast, y_death_forecast)
    
    forecasted[state] = (y_cum_case_forecast, y_cum_death_forecast)

## 2.4 Generate Submission File

In [ ]:
forecastID = [x for x in range(forecast_days * 50)]
deaths = []
confirmed = []

for i in range(forecast_days):
    for s in states:
        print(f"Day {i+1}/26, {s}")
        confirmed.append(forecasted[s][0][i])
        deaths.append(forecasted[s][1][i])
        
final = pd.DataFrame(list(zip(forecastID, confirmed, deaths)), 
               columns =['ForecastID', 'Confirmed', 'Deaths']) 

final.to_csv("submission.csv", index=False)